import { useState, useEffect, useCallback } from "react";
const API = "http://localhost:3000/api";
const GOLD = "#d4af37";
const F = { sans: "Montserrat,sans-serif", serif: "'Cormorant Garamond',serif" };
const fmt = (n) => "€" + Number(n).toLocaleString("de-DE");
const TABS = [{ key: "fleet", label: "Fleet", icon: "◈" }, { key: "orders", label: "My Orders", icon: "◉" }, { key: "admin", label: "Inventory", icon: "◆" }];
const BASE_PRICES = { "bugatti-chiron": 4000000, "ferrari-roma": 300000, "pagani-huayra": 3000000, "rolls-royce-phantom": 450000, "toyota-supra-mk5": 400000, "koenigsegg-regera": 4000000, "lamborghini-veneno": 9000000, "aston-martin-valkyrie": 2500000, "hennessey-venom-f5": 1850000 };
const CONFIG = {
  colors:      [{ n: "Noir Obsidian", p: 0 }, { n: "Arctic White", p: 12000 }, { n: "Racing Red", p: 8000 }, { n: "Midnight Blue", p: 8000 }, { n: "Gold Edition", p: 25000 }, { n: "Matte Carbon", p: 18000 }],
  interiors:   [{ n: "Black Leather", p: 0 }, { n: "Cream Nappa", p: 15000 }, { n: "Red Alcantara", p: 22000 }, { n: "Carbon Fiber", p: 35000 }],
  performance: [{ n: "Standard", p: 0 }, { n: "Sport Package", p: 45000 }, { n: "Track Edition", p: 85000 }, { n: "Ultimate", p: 140000 }],
  wheels:      [{ n: "Standard Alloy", p: 0 }, { n: "Forged Carbon", p: 18000 }, { n: "Titanium Sport", p: 28000 }, { n: "Signature Edition", p: 42000 }],
};
function Toast({ msg, type, onClose }) {
  useEffect(() => { const t = setTimeout(onClose, 3500); return () => clearTimeout(t); }, [onClose]);
  return <div style={{ position:"fixed",top:"2rem",right:"2rem",zIndex:9999,background:type==="success"?"rgba(212,175,55,0.12)":"rgba(200,50,50,0.12)",border:type==="success"?"1px solid rgba(212,175,55,0.5)":"1px solid rgba(200,50,50,0.5)",padding:"1rem 1.5rem",maxWidth:"340px",animation:"toastIn 0.4s ease" }}><div style={{ fontFamily:F.sans,fontSize:"0.62rem",letterSpacing:"0.1em",color:type==="success"?GOLD:"#e88" }}>{msg}</div></div>;
}
function PurchaseModal({ vehicle, onConfirm, onClose }) {
  const [color,setColor]=useState(0);const [inter,setInter]=useState(0);const [perf,setPerf]=useState(0);const [wheel,setWheel]=useState(0);const [loading,setLoading]=useState(false);
  const base=BASE_PRICES[vehicle.slug]||0;
  const total=base+CONFIG.colors[color].p+CONFIG.interiors[inter].p+CONFIG.performance[perf].p+CONFIG.wheels[wheel].p;
  const handleBuy=async()=>{ setLoading(true); await onConfirm({ vehicle_slug:vehicle.slug,vehicle_model:vehicle.model,price:vehicle.valuation,color:CONFIG.colors[color].n,interior:CONFIG.interiors[inter].n,performance:CONFIG.performance[perf].n,wheels:CONFIG.wheels[wheel].n,total_price:total }); setLoading(false); };
  const BtnRow=({items,active,setActive})=><div style={{display:"flex",gap:"0.5rem",flexWrap:"wrap"}}>{items.map((o,i)=><button key={i} onClick={()=>setActive(i)} style={{background:active===i?"rgba(212,175,55,0.1)":"rgba(255,255,255,0.02)",border:active===i?"1px solid rgba(212,175,55,0.6)":"1px solid rgba(255,255,255,0.08)",color:active===i?GOLD:"#555",padding:"0.5rem 0.9rem",fontFamily:F.sans,fontSize:"0.58rem",letterSpacing:"0.12em",textTransform:"uppercase",cursor:"pointer"}}>{o.n}{o.p>0?`  +${fmt(o.p)}`:""}</button>)}</div>;
  return <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,0.88)",zIndex:1000,display:"flex",alignItems:"center",justifyContent:"center",padding:"1rem"}}><div style={{background:"#0a0a0a",border:"1px solid rgba(212,175,55,0.2)",width:"100%",maxWidth:"700px",maxHeight:"90vh",overflowY:"auto",animation:"modalIn 0.4s ease"}}><div style={{padding:"1.8rem 2rem",borderBottom:"1px solid rgba(255,255,255,0.05)",display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontFamily:F.sans,fontSize:"0.5rem",letterSpacing:"0.4em",color:"#555",marginBottom:"0.3rem",textTransform:"uppercase"}}>Configure & Purchase</div><div style={{fontFamily:F.serif,fontSize:"1.6rem",color:"#fff"}}>{vehicle.model}</div></div><button onClick={onClose} style={{background:"none",border:"none",color:"#444",fontSize:"1.5rem",cursor:"pointer"}}>×</button></div><div style={{padding:"1.5rem 2rem",display:"flex",flexDirection:"column",gap:"1.5rem"}}>{[{label:"Exterior Color",items:CONFIG.colors,active:color,set:setColor},{label:"Interior",items:CONFIG.interiors,active:inter,set:setInter},{label:"Performance",items:CONFIG.performance,active:perf,set:setPerf},{label:"Wheels & Kit",items:CONFIG.wheels,active:wheel,set:setWheel}].map(({label,items,active,set})=><div key={label}><div style={{fontFamily:F.sans,fontSize:"0.5rem",letterSpacing:"0.4em",color:"#444",textTransform:"uppercase",marginBottom:"0.7rem"}}>{label}</div><BtnRow items={items} active={active} setActive={set}/></div>)}</div><div style={{padding:"1.5rem 2rem",borderTop:"1px solid rgba(255,255,255,0.05)",background:"rgba(212,175,55,0.02)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-end",marginBottom:"1.2rem"}}><div style={{fontFamily:F.sans,fontSize:"0.5rem",letterSpacing:"0.4em",color:"#555",textTransform:"uppercase"}}>Total Configuration</div><div style={{fontFamily:F.serif,fontSize:"2rem",color:GOLD}}>{fmt(total)}</div></div><div style={{display:"flex",gap:"0.8rem"}}><button onClick={onClose} style={{flex:1,padding:"0.9rem",background:"none",border:"1px solid rgba(255,255,255,0.08)",color:"#444",fontFamily:F.sans,fontSize:"0.58rem",letterSpacing:"0.2em",textTransform:"uppercase",cursor:"pointer"}}>Cancel</button><button onClick={handleBuy} disabled={loading} style={{flex:2,padding:"0.9rem",background:"rgba(212,175,55,0.15)",border:"1px solid rgba(212,175,55,0.5)",color:GOLD,fontFamily:F.sans,fontSize:"0.58rem",letterSpacing:"0.2em",textTransform:"uppercase",cursor:loading?"not-allowed":"pointer"}}>{loading?"Processing...":"Confirm Purchase →"}</button></div></div></div></div>;
}
function FleetTab({ vehicles, onBuy }) {
  return <div><p style={{fontFamily:F.sans,fontSize:"0.58rem",letterSpacing:"0.3em",color:"#444",textTransform:"uppercase",marginBottom:"2rem",textAlign:"center"}}>Select a vehicle to configure and purchase</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(280px,1fr))",gap:"1rem"}}>{vehicles.map((v)=>{ const stockNum=parseInt(v.stock)||0;const soldOut=stockNum===0;return <div key={v.slug} style={{border:"1px solid rgba(255,255,255,0.06)",background:"#080808",padding:"1.5rem",display:"flex",flexDirection:"column",gap:"0.8rem",opacity:soldOut?0.45:1}} onMouseEnter={e=>!soldOut&&(e.currentTarget.style.borderColor="rgba(212,175,55,0.3)")} onMouseLeave={e=>(e.currentTarget.style.borderColor="rgba(255,255,255,0.06)")}><div style={{fontFamily:F.serif,fontSize:"1.3rem",color:"#ddd"}}>{v.model}</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><span style={{fontFamily:F.sans,fontSize:"0.9rem",color:GOLD}}>{v.valuation}</span><span style={{fontFamily:F.sans,fontSize:"0.55rem",letterSpacing:"0.15em",color:soldOut?"#c00":"#5a5",padding:"0.3rem 0.7rem",border:`1px solid ${soldOut?"rgba(200,0,0,0.3)":"rgba(80,180,80,0.3)"}`}}>{soldOut?"SOLD OUT":v.stock}</span></div><button onClick={()=>!soldOut&&onBuy(v)} disabled={soldOut} style={{marginTop:"0.5rem",padding:"0.75rem",background:"none",border:`1px solid ${soldOut?"rgba(255,255,255,0.05)":"rgba(212,175,55,0.35)"}`,color:soldOut?"#333":GOLD,fontFamily:F.sans,fontSize:"0.58rem",letterSpacing:"0.2em",textTransform:"uppercase",cursor:soldOut?"not-allowed":"pointer"}} onMouseEnter={e=>!soldOut&&(e.currentTarget.style.background="rgba(212,175,55,0.08)")} onMouseLeave={e=>!soldOut&&(e.currentTarget.style.background="none")}>{soldOut?"Unavailable":"Configure & Purchase →"}</button></div>; })}</div></div>;
}
function OrdersTab({ orders, onCancel, loading }) {
  if (loading) return <p style={{color:"#444",fontFamily:F.sans,fontSize:"0.65rem",textAlign:"center",padding:"3rem"}}>Loading...</p>;
  if (orders.length===0) return <div style={{textAlign:"center",padding:"4rem",color:"#333"}}><div style={{fontFamily:F.serif,fontSize:"3rem",color:"rgba(212,175,55,0.1)",marginBottom:"1rem"}}>◇</div><p style={{fontFamily:F.sans,fontSize:"0.65rem",letterSpacing:"0.2em",textTransform:"uppercase"}}>No orders yet</p></div>;
  return <div style={{display:"flex",flexDirection:"column",gap:"1rem"}}>{orders.map(o=><div key={o.id} style={{border:"1px solid rgba(212,175,55,0.12)",background:"#080808",padding:"1.5rem",display:"grid",gridTemplateColumns:"1fr auto",gap:"1rem",alignItems:"start"}}><div><div style={{display:"flex",alignItems:"center",gap:"1rem",marginBottom:"0.8rem"}}><span style={{fontFamily:F.serif,fontSize:"1.2rem",color:"#ddd"}}>{o.vehicle_model}</span><span style={{fontFamily:F.sans,fontSize:"0.48rem",letterSpacing:"0.2em",color:"#5a5",border:"1px solid rgba(80,180,80,0.3)",padding:"0.2rem 0.6rem"}}>CONFIRMED</span></div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(160px,1fr))",gap:"0.5rem",marginBottom:"0.8rem"}}>{[{l:"Color",v:o.color},{l:"Interior",v:o.interior},{l:"Performance",v:o.performance},{l:"Wheels",v:o.wheels}].map(({l,v})=>v&&<div key={l}><div style={{fontFamily:F.sans,fontSize:"0.45rem",letterSpacing:"0.2em",color:"#444",textTransform:"uppercase"}}>{l}</div><div style={{fontFamily:F.sans,fontSize:"0.65rem",color:"#888"}}>{v}</div></div>)}</div><div style={{fontFamily:F.sans,fontSize:"0.55rem",color:"#444"}}>{new Date(o.created_at).toLocaleDateString("es-ES",{day:"2-digit",month:"long",year:"numeric",hour:"2-digit",minute:"2-digit"})} · Order #{String(o.id).padStart(4,"0")}</div></div><div style={{textAlign:"right"}}><div style={{fontFamily:F.serif,fontSize:"1.5rem",color:GOLD,marginBottom:"0.8rem"}}>{fmt(o.total_price)}</div><button onClick={()=>onCancel(o.id)} style={{padding:"0.5rem 1rem",background:"none",border:"1px solid rgba(200,50,50,0.3)",color:"#c55",fontFamily:F.sans,fontSize:"0.5rem",letterSpacing:"0.15em",textTransform:"uppercase",cursor:"pointer"}} onMouseEnter={e=>(e.currentTarget.style.background="rgba(200,50,50,0.08)")} onMouseLeave={e=>(e.currentTarget.style.background="none")}>Cancel Order</button></div></div>)}</div>;
}
function AdminTab({ vehicles, onStockChange }) {
  const [changes,setChanges]=useState({});const [saving,setSaving]=useState(false);
  const handleChange=(slug,val)=>{ const n=parseInt(val);if(!isNaN(n)&&n>=0)setChanges(prev=>({...prev,[slug]:n})); };
  const handleSave=async(slug)=>{ const newQty=changes[slug];if(newQty===undefined)return;setSaving(true);await onStockChange(slug,newQty);setChanges(prev=>{const c={...prev};delete c[slug];return c;});setSaving(false); };
  return <div><p style={{fontFamily:F.sans,fontSize:"0.55rem",letterSpacing:"0.3em",color:"#444",textTransform:"uppercase",marginBottom:"1.5rem"}}>Manage inventory stock levels</p><div style={{display:"flex",flexDirection:"column",gap:"0.6rem"}}>{vehicles.map(v=>{ const stockNum=parseInt(v.stock)||0;const hasPending=changes[v.slug]!==undefined;return <div key={v.slug} style={{display:"grid",gridTemplateColumns:"1fr auto auto",gap:"1rem",alignItems:"center",padding:"1rem 1.2rem",border:"1px solid rgba(255,255,255,0.05)",background:"#080808"}}><div><div style={{fontFamily:F.serif,fontSize:"1.1rem",color:"#ccc"}}>{v.model}</div><div style={{fontFamily:F.sans,fontSize:"0.55rem",color:stockNum===0?"#c55":"#5a5",marginTop:"0.2rem"}}>{stockNum===0?"SOLD OUT":`${stockNum} in stock`}</div></div><input type="number" min="0" max="99" defaultValue={stockNum} onChange={e=>handleChange(v.slug,e.target.value)} style={{width:"70px",padding:"0.5rem",background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.1)",color:"#ddd",fontFamily:F.sans,fontSize:"0.7rem",textAlign:"center"}}/><button onClick={()=>handleSave(v.slug)} disabled={!hasPending||saving} style={{padding:"0.5rem 1rem",background:hasPending?"rgba(212,175,55,0.1)":"none",border:`1px solid ${hasPending?"rgba(212,175,55,0.4)":"rgba(255,255,255,0.06)"}`,color:hasPending?GOLD:"#333",fontFamily:F.sans,fontSize:"0.5rem",letterSpacing:"0.15em",textTransform:"uppercase",cursor:hasPending?"pointer":"not-allowed"}}>Save</button></div>; })}</div></div>;
}
export default function PurchaseMenu() {
  const [tab,setTab]=useState("fleet");const [vehicles,setVehicles]=useState([]);const [orders,setOrders]=useState([]);const [modal,setModal]=useState(null);const [toast,setToast]=useState(null);const [loadOrders,setLoadOrders]=useState(false);
  const notify=(msg,type="success")=>setToast({msg,type});
  const fetchVehicles=useCallback(()=>{ fetch(`${API}/vehicles`).then(r=>r.json()).then(setVehicles).catch(()=>notify("Error loading vehicles","error")); },[]);
  const fetchOrders=useCallback(()=>{ setLoadOrders(true);fetch(`${API}/orders`).then(r=>r.json()).then(data=>{setOrders(data);setLoadOrders(false);}).catch(()=>{notify("Error loading orders","error");setLoadOrders(false);}); },[]);
  useEffect(()=>{fetchVehicles();},[fetchVehicles]);
  useEffect(()=>{ if(tab==="orders"||tab==="admin"){fetchOrders();} },[tab,fetchOrders]);
  const handlePurchase=async(orderData)=>{ try{ const res=await fetch(`${API}/orders`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(orderData)});const data=await res.json();if(!res.ok)throw new Error(data.error||"Purchase failed");notify(`✓ ${orderData.vehicle_model} purchased!`);setModal(null);fetchVehicles();if(tab==="orders")fetchOrders(); }catch(err){notify(err.message,"error");} };
  const handleCancel=async(orderId)=>{ try{ const res=await fetch(`${API}/orders/${orderId}`,{method:"DELETE"});const data=await res.json();if(!res.ok)throw new Error(data.error||"Cancel failed");notify("Order cancelled · Stock restored");fetchOrders();fetchVehicles(); }catch(err){notify(err.message,"error");} };
  const handleStockChange=async(slug,newQty)=>{ const newStr=newQty===1?"1 Unit Available":`${newQty} Units Available`;try{ const res=await fetch(`${API}/vehicles/${slug}/stock`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({stock:newStr})});if(!res.ok)throw new Error("Stock update failed");notify("Stock updated");fetchVehicles(); }catch(err){notify(err.message,"error");} };
  return(
    <section style={{background:"#000",minHeight:"100vh",padding:"0 0 120px",fontFamily:F.sans}}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@300;400;600&family=Montserrat:wght@300;400;500;600&display=swap');@keyframes toastIn{from{opacity:0;transform:translateY(-12px)}to{opacity:1;transform:none}}@keyframes modalIn{from{opacity:0;transform:scale(0.96)}to{opacity:1;transform:scale(1)}}`}</style>
      {toast&&<Toast msg={toast.msg} type={toast.type} onClose={()=>setToast(null)}/>}
      {modal&&<PurchaseModal vehicle={modal} onConfirm={handlePurchase} onClose={()=>setModal(null)}/>}
      <div style={{padding:"80px 40px 0",textAlign:"center",background:"radial-gradient(ellipse at top,rgba(212,175,55,0.05) 0%,transparent 60%)"}}>
        <div style={{fontSize:"0.55rem",letterSpacing:"0.5em",color:"#444",textTransform:"uppercase",marginBottom:"0.8rem"}}>Francis Luxor Motors</div>
        <h2 style={{fontFamily:F.serif,fontSize:"clamp(2.5rem,6vw,4.5rem)",fontWeight:300,letterSpacing:"6px",color:"#fff",marginBottom:"0.5rem"}}>Acquisition Portal</h2>
        <div style={{width:"60px",height:"1px",background:`linear-gradient(to right,transparent,${GOLD},transparent)`,margin:"0 auto 2.5rem"}}/>
      </div>
      <div style={{display:"flex",justifyContent:"center",gap:"0",borderBottom:"1px solid rgba(255,255,255,0.05)",marginBottom:"3rem"}}>
        {TABS.map(t=>{ const active=tab===t.key;return <button key={t.key} onClick={()=>setTab(t.key)} style={{background:active?"rgba(212,175,55,0.06)":"none",border:"none",borderBottom:active?`1px solid ${GOLD}`:"1px solid transparent",color:active?GOLD:"#444",padding:"1rem 2.5rem",fontFamily:F.sans,fontSize:"0.58rem",letterSpacing:"0.25em",textTransform:"uppercase",cursor:"pointer",display:"flex",alignItems:"center",gap:"0.6rem"}}><span>{t.icon}</span>{t.label}{t.key==="orders"&&orders.length>0&&<span style={{background:GOLD,color:"#000",borderRadius:"50%",width:"18px",height:"18px",fontSize:"0.5rem",display:"flex",alignItems:"center",justifyContent:"center",fontWeight:600}}>{orders.length}</span>}</button>; })}
      </div>
      <div style={{maxWidth:"1200px",margin:"0 auto",padding:"0 40px"}}>
        {tab==="fleet"&&<FleetTab vehicles={vehicles} onBuy={setModal}/>}
        {tab==="orders"&&<OrdersTab orders={orders} onCancel={handleCancel} loading={loadOrders}/>}
        {tab==="admin"&&<AdminTab vehicles={vehicles} onStockChange={handleStockChange}/>}
      </div>
    </section>
  );
}
