export const VEHICLES = [
  { id: 1, slug: "bugatti-chiron", model: "Bugatti Chiron", valuation: "€4,000,000", stock: "5 Units Available", description: "The pinnacle of automotive engineering featuring a quad-turbocharged W16 powerplant and unparalleled luxury.", engineDesc: "Corazon W16 de 8.0L: Una obra maestra de ingenieria con 4 turbocompresores y refrigeracion liquida avanzada.", hp: "1500", top: "420", accent: "#ff3e3e" },
  { id: 2, slug: "ferrari-roma", model: "Ferrari Roma", valuation: "€300,000", stock: "15 Units Available", description: "A contemporary representation of the 'La Nuova Dolce Vita', combining timeless elegance with a high-performance V8.", engineDesc: "V8 Turbo de 3.9L: Elegancia italiana con una respuesta de aceleracion instantanea y sonido sinfonico.", hp: "620", top: "320", accent: "#ffff00" },
  { id: 3, slug: "pagani-huayra", model: "Pagani Huayra", valuation: "€3,000,000", stock: "3 Units Available", description: "A masterful fusion of art and science, handcrafted with an AMG-sourced V12 and active aerodynamics.", engineDesc: "V12 Biturbo de Mercedes-AMG: Ligereza extrema y aerodinamica activa en cada centimetro de fibra de carbono.", hp: "800", top: "380", accent: "#00f2ff" },
  { id: 4, slug: "rolls-royce-phantom", model: "Rolls-Royce Phantom", valuation: "€450,000", stock: "5 Units Available", description: "The definitive symbol of opulence and bespoke craftsmanship, offering an effortless Magic Carpet Ride.", engineDesc: "V12 de 6.75L: El epitome del refinamiento britanico. Un motor que susurra poder garantizando el legendario Magic Carpet Ride.", hp: "571", top: "250", accent: "#c9b037" },
  { id: 5, slug: "toyota-supra-mk5", model: "Toyota Supra MK5", valuation: "€400,000", stock: "9 Units Available", description: "Precision-engineered sports performance featuring a signature straight-six turbocharged engine and track-focused agility.", engineDesc: "Motor 6 cilindros en linea (B58) de 3.0L Twin-Scroll Turbo: Desarrollado por BMW y optimizado por Toyota.", hp: "382", top: "250", accent: "#ff3d00" },
  { id: 6, slug: "koenigsegg-regera", model: "Koenigsegg Regera", valuation: "€4,000,000", stock: "1 Unit Available", description: "An innovative plug-in hybrid megacar utilizing the Direct Drive system to redefine hypercar acceleration.", engineDesc: "V8 Twin-Turbo Hibrido: Innovacion sueca revolucionaria con sistema Direct Drive. 1500 HP combustion mas 700 HP electricos.", hp: "2200", top: "410", accent: "#d4af37" },
  { id: 7, slug: "lamborghini-veneno", model: "Lamborghini Veneno", valuation: "€9,000,000", stock: "2 Units Available", description: "An ultra-exclusive tribute to aeronautical design, pushing the boundaries of the naturally aspirated V12.", engineDesc: "V12 Aspirado de 6.5L: Pura brutalidad italiana sin asistencia artificial. Cada revolucion es un grito de guerra.", hp: "750", top: "355", accent: "#00ff41" },
  { id: 8, slug: "aston-martin-valkyrie", model: "Aston Martin Valkyrie", valuation: "€2,500,000", stock: "8 Units Available", description: "Born from a collaboration with Red Bull Racing, this F1-inspired masterpiece delivers raw, track-oriented performance.", engineDesc: "V12 Hibrido Cosworth de 6.5L: Desarrollado con Red Bull Racing, aspira naturalmente hasta 11,100 RPM.", hp: "1160", top: "400", accent: "#00d9ff" },
  { id: 9, slug: "hennessey-venom-f5", model: "Hennessey Venom F5", valuation: "€1,850,000", stock: "2 Units Available", description: "The Hennessey Venom F5 is an ultra-high-performance hypercar built for extreme speed with over 1,800 horsepower.", engineDesc: "V8 Twin-Turbo Fury de 6.6L: Disenado por Hennessey para romper records de velocidad. Mas de 1800 HP en chasis de fibra de carbono.", hp: "1817", top: "484", accent: "#ff1744" },
];
